### ISSUE TITLE
Question: Is fine tuning suitable for factual answers from custom data, or is it better to use vector databases and use only the relevant chunk in the prompt for factual answers?

### ISSUE THREAD

**Issue by petrbrzek** [lxe/simple-llm-finetuner#4]
I know that in the case of Open AI fine-tuning it doesn't work by providing my own data and then the model can use it. Rather, it works by teaching it what style of language to use. So if I want GPT to use my data, I have to automatically have embeddings and a vector database and then put the relevant chunk of data back into the GPT prompt.

Is it similar here?

**Comment by brunosan** [comment]
IMO if factual answers restricted to a known set are needed, the only way to be sure is to use vector embedding hits, and then use the token generation prompt to make a summary only with given text, and  temp=0.
